/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ctinfoexport;

import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.google.common.io.LittleEndianDataOutputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Roco
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exMapType = new javax.swing.ButtonGroup();
        weatherType = new javax.swing.ButtonGroup();
        cannonType = new javax.swing.ButtonGroup();
        saveDiag = new javax.swing.JFileChooser();
        globalMapRot = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        localMinX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        localMinY = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        localMaxY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        localMaxX = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        globalMinY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        globalMaxY = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        globalMaxX = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        globalMinX = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        exMaxY = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        exMaxX = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        exMinX = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        exMinY = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        exType = new javax.swing.JRadioButton();
        lyrType = new javax.swing.JRadioButton();
        bgType = new javax.swing.JRadioButton();
        aBgType = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        boundMinX = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        boundMinY = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        boundMinZ = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        boundMaxY = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        boundMaxZ = new javax.swing.JTextField();
        boundMaxX = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        seqID = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        bnkID = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        rainType = new javax.swing.JRadioButton();
        snowType = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        cannonBh = new javax.swing.JRadioButton();
        warpBh = new javax.swing.JRadioButton();
        partialFog = new javax.swing.JCheckBox();
        partialFogV = new javax.swing.JCheckBox();
        normalType = new javax.swing.JRadioButton();
        songSel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        noRot = new javax.swing.JRadioButton();
        rotClock = new javax.swing.JRadioButton();
        rotCounter = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newOpt = new javax.swing.JMenuItem();
        openOpt = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        saveOpt = new javax.swing.JMenuItem();
        saveAsOpt = new javax.swing.JMenuItem();

        saveDiag.setAccessory(saveOpt);
        saveDiag.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveDiag.setDialogTitle("");
        saveDiag.setFileFilter(new FileNameExtensionFilter("Course information file (*.nkldr)","nkldr"));
        saveDiag.setSelectedFile(new java.io.File("/var/home/Roco/course_info.nkldr"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("course_info.nkldr editor");
        setResizable(false);

        jLabel1.setText("Top-Left");

        localMinX.setColumns(7);
        localMinX.setText("0");

        jLabel2.setText("Local Map");

        jLabel3.setText("X");

        localMinY.setColumns(7);
        localMinY.setText("0");

        jLabel4.setText("Y");

        localMaxY.setColumns(7);
        localMaxY.setText("0");

        jLabel5.setText("Y");

        jLabel6.setText("Bottom-Right");

        localMaxX.setColumns(7);
        localMaxX.setText("0");
        localMaxX.addActionListener(this::localMaxXActionPerformed);

        jLabel7.setText("X");

        globalMinY.setColumns(7);
        globalMinY.setText("0");

        jLabel8.setText("Y");

        globalMaxY.setColumns(7);
        globalMaxY.setText("0");

        jLabel9.setText("Y");

        jLabel10.setText("Top-Left");

        jLabel11.setText("Bottom-Right");

        globalMaxX.setColumns(7);
        globalMaxX.setText("0");

        jLabel12.setText("X");

        globalMinX.setColumns(7);
        globalMinX.setText("0");

        jLabel13.setText("Global Map");

        jLabel14.setText("X");

        exMaxY.setColumns(7);
        exMaxY.setText("0");
        exMaxY.setEnabled(false);

        jLabel15.setText("Y");

        jLabel16.setText("Top-Left");

        jLabel17.setText("Bottom-Right");

        exMaxX.setColumns(7);
        exMaxX.setText("0");
        exMaxX.setEnabled(false);

        jLabel18.setText("X");

        exMinX.setColumns(7);
        exMinX.setText("0");
        exMinX.setEnabled(false);

        jLabel19.setText("Extended Local Map");

        exMinY.setColumns(7);
        exMinY.setText("0");
        exMinY.setEnabled(false);

        jLabel20.setText("Y");

        jLabel21.setText("Type");

        exMapType.add(exType);
        exType.setText("Extended");
        exType.setToolTipText("Used in tracks like GCN Luigi Circuit or DK Pass");
        exType.addActionListener(this::exMapTypeActionPerformed);

        exMapType.add(lyrType);
        lyrType.setText("Layer");
        lyrType.setToolTipText("Used in Airship Fortress and Tick-Tock Clock");
        lyrType.addActionListener(this::exMapTypeActionPerformed);

        exMapType.add(bgType);
        bgType.setText("Background");
        bgType.setToolTipText("Used in Mario Circuit");
        bgType.addActionListener(this::exMapTypeActionPerformed);

        exMapType.add(aBgType);
        aBgType.setText("Animated Background");
        aBgType.setToolTipText("Used in Big Bully Arena");
        aBgType.addActionListener(this::exMapTypeActionPerformed);

        jLabel22.setText("X");

        boundMinX.setColumns(5);
        boundMinX.setText("0");
        boundMinX.setEnabled(false);
        boundMinX.addActionListener(this::boundMinXActionPerformed);

        jLabel23.setText("X");

        jLabel24.setText("Y");

        boundMinY.setColumns(5);
        boundMinY.setText("-Infinite");
        boundMinY.setEnabled(false);
        boundMinY.addActionListener(this::boundMinYActionPerformed);

        jLabel25.setText("Z");

        boundMinZ.setColumns(5);
        boundMinZ.setText("0");
        boundMinZ.setEnabled(false);
        boundMinZ.addActionListener(this::boundMinZActionPerformed);

        jLabel26.setText("X");

        jLabel27.setText("Y");

        boundMaxY.setColumns(5);
        boundMaxY.setText("0");
        boundMaxY.setEnabled(false);
        boundMaxY.addActionListener(this::boundMaxYActionPerformed);

        jLabel28.setText("Z");

        boundMaxZ.setColumns(5);
        boundMaxZ.setText("0");
        boundMaxZ.setEnabled(false);
        boundMaxZ.addActionListener(this::boundMaxZActionPerformed);

        boundMaxX.setColumns(5);
        boundMaxX.setText("0");
        boundMaxX.setEnabled(false);
        boundMaxX.addActionListener(this::boundMaxXActionPerformed);

        jLabel29.setText("Layer bounds (The local map will be swapped when the driver is inside this box)");

        jLabel30.setText("Min. Coord (\"Bottom-Left\")");

        jLabel31.setText("Max. Coord (\"Top-Right\")");

        jLabel33.setText("Sound");

        jLabel34.setText("Sequence ID");

        seqID.setColumns(3);
        seqID.setText("74");
        seqID.setToolTipText("");

        jLabel35.setText("SFX Bank ID");

        bnkID.setColumns(3);
        bnkID.setText("255");
        bnkID.setToolTipText("");
        bnkID.addActionListener(this::bnkIDActionPerformed);

        jLabel32.setText("Misc");

        jLabel36.setText("Weather");

        weatherType.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("None");
        jRadioButton5.addActionListener(this::jRadioButton5ActionPerformed);

        weatherType.add(rainType);
        rainType.setText("Rain");

        weatherType.add(snowType);
        snowType.setText("Snow");

        jLabel37.setText("Cannon Behavior");

        cannonType.add(cannonBh);
        cannonBh.setSelected(true);
        cannonBh.setText("Normal");

        cannonType.add(warpBh);
        warpBh.setText("Warp pipe");

        partialFog.setText("Course model has partial Fog");

        partialFogV.setText("SkyBox has partial fog");

        exMapType.add(normalType);
        normalType.setSelected(true);
        normalType.setText("None");
        normalType.addActionListener(this::exMapTypeActionPerformed);

        songSel.setText("Song List");
        songSel.addActionListener(this::songSelActionPerformed);

        jButton1.setText("SFX List");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel38.setText("Global Map Rotation");

        globalMapRot.add(noRot);
        noRot.setSelected(true);
        noRot.setText("None");

        globalMapRot.add(rotClock);
        rotClock.setText("Clockwise");

        globalMapRot.add(rotCounter);
        rotCounter.setText("Counterclockwise");

        fileMenu.setText("File");

        newOpt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        newOpt.setText("New");
        newOpt.addActionListener(this::newOptActionPerformed);
        fileMenu.add(newOpt);

        openOpt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openOpt.setText("Open");
        openOpt.addActionListener(this::openOptActionPerformed);
        fileMenu.add(openOpt);

        jMenuItem1.setText("Import .json");
        fileMenu.add(jMenuItem1);

        jMenuItem2.setText("Import from arm9.bin");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        fileMenu.add(jMenuItem2);

        saveOpt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveOpt.setText("Save");
        saveOpt.setToolTipText("");
        saveOpt.addActionListener(this::saveOptActionPerformed);
        fileMenu.add(saveOpt);

        saveAsOpt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveAsOpt.setText("Save as...");
        saveAsOpt.addActionListener(this::saveAsOptActionPerformed);
        fileMenu.add(saveAsOpt);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boundMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boundMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boundMinZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boundMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boundMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boundMaxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(globalMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(globalMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(globalMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(globalMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(exMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel29)
                            .addComponent(jLabel33)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(normalType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lyrType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bgType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aBgType))
                            .addComponent(jLabel21)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seqID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(songSel)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButton5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rainType))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel37)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cannonBh)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(snowType)
                                            .addComponent(warpBh)))
                                    .addComponent(jLabel32)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(noRot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rotClock)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rotCounter)
                                    .addComponent(partialFogV)
                                    .addComponent(partialFog))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(localMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(localMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(localMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(localMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(globalMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(globalMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(globalMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(globalMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exType)
                    .addComponent(lyrType)
                    .addComponent(bgType)
                    .addComponent(aBgType)
                    .addComponent(normalType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(exMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(exMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(exMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boundMinX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(boundMinY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(boundMinZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boundMaxX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(boundMaxY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(boundMaxZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(seqID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(bnkID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(songSel)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jRadioButton5)
                    .addComponent(rainType)
                    .addComponent(snowType)
                    .addComponent(partialFog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(cannonBh)
                    .addComponent(warpBh)
                    .addComponent(partialFogV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(noRot)
                    .addComponent(rotClock)
                    .addComponent(rotCounter))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean hasSaved = false;
    int overwrite = JOptionPane.NO_OPTION;
    
    private void setupInfo(CourseInfo info)
    {
        info.localMap = new MapScale(
        new Coord2D(
            Integer.parseInt(localMinX.getText()),
            Integer.parseInt(localMinY.getText())),
        new Coord2D(
            Integer.parseInt(localMaxX.getText()),
            Integer.parseInt(localMaxY.getText()))
        );
        
        info.globalMap = new MapScale(
        new Coord2D(
            Integer.parseInt(globalMinX.getText()),
            Integer.parseInt(globalMinY.getText())),
        new Coord2D(
            Integer.parseInt(globalMaxX.getText()),
            Integer.parseInt(globalMaxY.getText()))
        );
        
        info.exMap = new MapScale(
        new Coord2D(
            Integer.parseInt(exMinX.getText()),
            Integer.parseInt(exMinY.getText())),
        new Coord2D(
            Integer.parseInt(exMaxX.getText()),
            Integer.parseInt(exMaxY.getText()))
        );
        
        info.exMapBounds = new MapBounds(
        new Coord3D(
            Integer.parseInt(boundMinX.getText()),
            0,
            Integer.parseInt(boundMinZ.getText())),
        new Coord3D(
            Integer.parseInt(boundMaxX.getText()),
            Integer.parseInt(boundMaxY.getText()),
            Integer.parseInt(boundMaxZ.getText()))
        );
        
        info.seqID = Integer.parseInt(seqID.getText());
        info.bnkID = Integer.parseInt(bnkID.getText());
        
        
        if(rainType.isSelected())
        {
            info.weatherType = info.weatherType.WEATHER_TYPE_RAIN;
        }
        else if(snowType.isSelected())
        {
            info.weatherType = info.weatherType.WEATHER_TYPE_SNOW;
        }
        else
        {
            info.weatherType = info.weatherType.WEATHER_TYPE_NONE;
        }
        
        
        if(exType.isSelected())
        {
            info.exMapType = info.exMapType.EXMAP_TYPE_EXTEND;
        }
        else if(lyrType.isSelected())
        {
            info.exMapType  = info.exMapType.EXMAP_TYPE_LAYER;
        }
        else if(bgType.isSelected())
        {
            info.exMapType = info.exMapType.EXMAP_TYPE_BACKGROUND;
        }
        else if(aBgType.isSelected())
        {
            info.exMapType = info.exMapType.EXMAP_TYPE_ANIMBACKGROUND;
        }
        else
        {
            info.exMapType = info.exMapType.EXMAP_TYPE_NONE;
        }
        
        
        if(warpBh.isSelected())
        {
            info.cannonBehavior = info.cannonBehavior.CANNON_TYPE_WARP;
        }
        else
        {
            info.cannonBehavior = info.cannonBehavior.CANNON_TYPE_NORMAL;
        }
        
        
        if(rotClock.isSelected())
        {
            info.globalMapRotation = 1;
        }
        else if(rotCounter.isSelected())
        {
            info.globalMapRotation = 2;
        }
        else
        {
            info.globalMapRotation = 0;
        }
        
        info.partialFog = partialFog.isSelected() ? 1 : 0;
        info.partialFogV = partialFogV.isSelected() ? 1 : 0;
    }
    
    private void saveFile(File file, CourseInfo info)
    {
        try
        {
            LittleEndianDataOutputStream stream = new LittleEndianDataOutputStream(new FileOutputStream(file));
            //Header
            stream.writeInt(info.magic);
            stream.writeShort(info.version);
            stream.writeShort(info.flags);
            stream.writeLong(info.padding);

            //LocalMap
            stream.writeShort(info.localMap.min.x);
            stream.writeShort(info.localMap.min.y);
            stream.writeShort(info.localMap.max.x);
            stream.writeShort(info.localMap.max.y);

            //GlobalMap
            stream.writeShort(info.globalMap.min.x);
            stream.writeShort(info.globalMap.min.y);
            stream.writeShort(info.globalMap.max.x);
            stream.writeShort(info.globalMap.max.y);

            //Exmap
            stream.writeShort(info.exMap.min.x);
            stream.writeShort(info.exMap.min.y);
            stream.writeShort(info.exMap.max.x);
            stream.writeShort(info.exMap.max.y);

            //ExMap Bounds
            stream.writeInt(Fx32.fromInt(info.exMapBounds.min.x));
            stream.writeInt(Fx32.fromInt(info.exMapBounds.min.y));
            stream.writeInt(Fx32.fromInt(info.exMapBounds.min.z));
            stream.writeInt(Fx32.fromInt(info.exMapBounds.max.x));
            stream.writeInt(Fx32.fromInt(info.exMapBounds.max.y));
            stream.writeInt(Fx32.fromInt(info.exMapBounds.max.z));

            //music
            stream.writeByte(info.seqID);
            stream.writeByte(info.bnkID);

            //Other
            stream.writeByte(info.weatherType.ordinal());
            stream.writeByte(info.exMapType.ordinal());
            stream.writeByte(info.cannonBehavior.ordinal());
            stream.writeByte(info.globalMapRotation);
            stream.writeByte(info.partialFog);
            stream.writeByte(info.partialFogV);


        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    private void saveOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveOptActionPerformed
        boolean shouldSave = false;
        File file;
        CourseInfo info = new CourseInfo();
        setupInfo(info);
        if(!hasSaved)
        {
            int res = saveDiag.showSaveDialog(this);
            if(res == saveDiag.APPROVE_OPTION)
            {
                shouldSave = true;
            }
        }
        else
        {
            shouldSave = true;
        }
        
        if(shouldSave)
        {
            String path = saveDiag.getSelectedFile().getAbsolutePath();
            if(path.toLowerCase().endsWith(".nkldr"))
            {
                file = saveDiag.getSelectedFile();
            }
            else
            {
                file = new File(path + ".nkldr");
            }
            if(file.exists())
            {
                if(overwrite != JOptionPane.YES_OPTION)
                {
                    overwrite = JOptionPane.showConfirmDialog(this, "The file already exists. Overwrite?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(overwrite != JOptionPane.YES_OPTION)
                    {
                        return;
                    }
                }

            }
            System.out.println("Saving to: " + file.getAbsolutePath());
            saveFile(file, info);
            hasSaved = true;
        }
        
        
        
        
        
        
        System.out.println("Save");
    }//GEN-LAST:event_saveOptActionPerformed

    private void saveAsOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsOptActionPerformed
        boolean shouldSave = false;
        File file;
        CourseInfo info = new CourseInfo();
        setupInfo(info);
        int res = saveDiag.showSaveDialog(this);
        if(res == saveDiag.APPROVE_OPTION)
        {
            shouldSave = true;
        }
        
        if(shouldSave)
        {
            String path = saveDiag.getSelectedFile().getAbsolutePath();
            if(path.toLowerCase().endsWith(".nkldr"))
            {
                file = saveDiag.getSelectedFile();
            }
            else
            {
                file = new File(path + ".nkldr");
            }
            if(file.exists())
            {
                overwrite = JOptionPane.showConfirmDialog(this, "The file already exists. Overwrite?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(overwrite != JOptionPane.YES_OPTION)
                {
                    return;
                }
            }
            System.out.println("Saving to: " + file.getAbsolutePath());
            saveFile(file, info);
            hasSaved = true;
        }
        
        System.out.println("Save as");
    }//GEN-LAST:event_saveAsOptActionPerformed

    private void openOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openOptActionPerformed
        System.out.println("Open");
    }//GEN-LAST:event_openOptActionPerformed

    private void newOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOptActionPerformed
        System.out.println("New");
    }//GEN-LAST:event_newOptActionPerformed

    private void boundMinXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundMinXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundMinXActionPerformed

    private void boundMinYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundMinYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundMinYActionPerformed

    private void boundMinZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundMinZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundMinZActionPerformed

    private void boundMaxYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundMaxYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundMaxYActionPerformed

    private void boundMaxZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundMaxZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundMaxZActionPerformed

    private void boundMaxXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundMaxXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundMaxXActionPerformed

    private void bnkIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnkIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnkIDActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void localMaxXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localMaxXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localMaxXActionPerformed

    private void exMapTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exMapTypeActionPerformed
        if(exType.isSelected())
        {
            exMinX.setEnabled(true);
            exMinY.setEnabled(true);
            exMaxX.setEnabled(true);
            exMaxY.setEnabled(true);
            
            boundMinX.setEnabled(false);
            boundMinZ.setEnabled(false);
            boundMaxX.setEnabled(false);
            boundMaxY.setEnabled(false);
            boundMaxZ.setEnabled(false);
        }
        else if(lyrType.isSelected())
        {
            exMinX.setEnabled(false);
            exMinY.setEnabled(false);
            exMaxX.setEnabled(false);
            exMaxY.setEnabled(false);
            
            boundMinX.setEnabled(true);
            boundMinZ.setEnabled(true);
            boundMaxX.setEnabled(true);
            boundMaxY.setEnabled(true);
            boundMaxZ.setEnabled(true);
        }
        else
        {
            exMinX.setEnabled(false);
            exMinY.setEnabled(false);
            exMaxX.setEnabled(false);
            exMaxY.setEnabled(false);
            
            boundMinX.setEnabled(false);
            boundMinZ.setEnabled(false);
            boundMaxX.setEnabled(false);
            boundMaxY.setEnabled(false);
            boundMaxZ.setEnabled(false);
        }
    }//GEN-LAST:event_exMapTypeActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void songSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songSelActionPerformed
        String[] seqNames = {
            "SEQ_BEACH", "SEQ_JUNGLE", "SEQ_TOWN", "SEQ_AIRSHIP", "SEQ_STADIUM",
            "SEQ_GARDEN", "SEQ_OBAKE", "SEQ_CIRCUIT_SFC", "SEQ_BEACH_SFC", "SEQ_NOHARA_SFC",
            "SEQ_DART_SFC", "SEQ_CIRCUIT_AGB", "SEQ_KOOPA_AGB", "SEQ_SKY_AGB", "SEQ_MOUNTAIN",
            "SEQ_COUNTRY", "SEQ_SNOW_64", "SEQ_OBAKE_64", "SEQ_CIRCUIT_GC", "SEQ_BABYPARK",
            "SEQ_BRIDGE", "SEQ_RIDGEWAY", "SEQ_SNOW", "SEQ_DESERT", "SEQ_CLOCK", "SEQ_KOOPA",
            "SEQ_RAINBOW", "SEQ_WANWAN", "SEQ_MINIGAME", "SEQ_MISSION_RUN", "SEQ_MISSION_RUN_BOSS",
            "SEQ_CIRCUIT"
        };
        String sel = (String)JOptionPane.showInputDialog(this, "Select a song", null, JOptionPane.PLAIN_MESSAGE, null, seqNames, seqNames[0]);
        if(sel == null)
        {
            return;
        }
        int id = 0;
        for (int i = 0; i < seqNames.length; i++) {
            if(seqNames[i].equals(sel))
            {
                id = i;
            }
        }
        if(id == 31)
        {
            id+=28 + 15;
        }
        else
        {
            id+=15;
        }
        //if(id >= 0)
        seqID.setText(Integer.toString(id));
    }//GEN-LAST:event_songSelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] bankNames = {
            "BANK_SE_CROSS", "BANK_SE_BANK", "BANK_SE_BEACH", "BANK_SE_MANSION", "BANK_SE_DESERT",
            "BANK_SE_TOWN", "BANK_SE_PINBALL", "BANK_SE_BRIDGE", "BANK_SE_SNOW", "BANK_SE_CLOCK",
            "BANK_SE_MARIO", "BANK_SE_AIRSHIP", "BANK_SE_STADIUM", "BANK_SE_GARDEN", "BANK_SE_KOOPA",
            "BANK_SE_FARM", "BANK_SE_HYUDORO", "BANK_SE_LUIGI_AGB", "BANK_SE_MINIGAME", "BANK_SE_RAINBOW",
            "NO SFX"
        };
        String sel = (String)JOptionPane.showInputDialog(this, "Select a sound effect bank", null, JOptionPane.PLAIN_MESSAGE, null, bankNames, bankNames[0]);
        if(sel == null)
        {
            return;
        }
        int id = 0;
        for (int i = 0; i < bankNames.length; i++) {
            if(bankNames[i].equals(sel))
            {
                id = i;
            }
        }
        if(sel.equals(bankNames[18]))
        {
            id = 43;
        }
        else if(sel.equals(bankNames[19]))
        {
            id = 48;
        }
        else if(sel.equals(bankNames[20]))
        {
            id = 255;
        }
        else
        {
            id+=16;
        }
        //if(id >= 0)
        bnkID.setText(Integer.toString(id));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aBgType;
    private javax.swing.JRadioButton bgType;
    private javax.swing.JTextField bnkID;
    private javax.swing.JTextField boundMaxX;
    private javax.swing.JTextField boundMaxY;
    private javax.swing.JTextField boundMaxZ;
    private javax.swing.JTextField boundMinX;
    private javax.swing.JTextField boundMinY;
    private javax.swing.JTextField boundMinZ;
    private javax.swing.JRadioButton cannonBh;
    private javax.swing.ButtonGroup cannonType;
    private javax.swing.ButtonGroup exMapType;
    private javax.swing.JTextField exMaxX;
    private javax.swing.JTextField exMaxY;
    private javax.swing.JTextField exMinX;
    private javax.swing.JTextField exMinY;
    private javax.swing.JRadioButton exType;
    private javax.swing.JMenu fileMenu;
    private javax.swing.ButtonGroup globalMapRot;
    private javax.swing.JTextField globalMaxX;
    private javax.swing.JTextField globalMaxY;
    private javax.swing.JTextField globalMinX;
    private javax.swing.JTextField globalMinY;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField localMaxX;
    private javax.swing.JTextField localMaxY;
    private javax.swing.JTextField localMinX;
    private javax.swing.JTextField localMinY;
    private javax.swing.JRadioButton lyrType;
    private javax.swing.JMenuItem newOpt;
    private javax.swing.JRadioButton noRot;
    private javax.swing.JRadioButton normalType;
    private javax.swing.JMenuItem openOpt;
    private javax.swing.JCheckBox partialFog;
    private javax.swing.JCheckBox partialFogV;
    private javax.swing.JRadioButton rainType;
    private javax.swing.JRadioButton rotClock;
    private javax.swing.JRadioButton rotCounter;
    private javax.swing.JMenuItem saveAsOpt;
    private javax.swing.JFileChooser saveDiag;
    private javax.swing.JMenuItem saveOpt;
    private javax.swing.JTextField seqID;
    private javax.swing.JRadioButton snowType;
    private javax.swing.JButton songSel;
    private javax.swing.JRadioButton warpBh;
    private javax.swing.ButtonGroup weatherType;
    // End of variables declaration//GEN-END:variables
}
